clientapp/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt


app_name = 'clientapp'
urlpatterns = [
    path(r'', views.Accueil.as_view(), name='index'),
    path(r'aide', views.Aide.as_view(), name='aide'),
    path(r'bienvenu', csrf_exempt(views.ArriveeDepartUtilisateur.as_view()), name='welcome'),
    path(r'accueilJS', views.AccueilJS.as_view(), name='indexJS'),
    path(r'connexion', csrf_exempt(views.ClientLogin.as_view()), name='log'),
    path(r'message', views.MessageAccueil.as_view(), name='message'),
    path(r'user', views.Profil.as_view(), name='user'),
    path(r'statistiques', views.Stats.as_view(), name='stats'),
    path(r'machine', views.ListeMachines.as_view(), name="machineuser"),
    path(r'panne/<int:pk>', views.DeclarationPanne.as_view(), name="panne"),
    path(r'panneview/<int:pk>', views.PanneView.as_view(), name="panneview"),

    path(r'borneclient',views.Websocket.as_view(),name="borneclient")
]

configuration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from rest_framework import routers
from fabaccess import views
from django.views.decorators.csrf import csrf_exempt
from rest_framework_swagger.views import get_swagger_view
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'userdata', views.UserdataViewSet)
router.register(r'machine', views.MachineViewSet)
router.register(r'registremanchine', views.RegistreMachineViewSet)
router.register(r'registreentree', views.RegistreEntreeViewSet)
router.register(r'panne', views.PanneViewSet)
router.register(r'droit', views.DroitViewSet)

schema_view = get_swagger_view(title='Fabacces API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientapp.urls')),
    path('api/',include(router.urls)),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'machine/init', csrf_exempt(views.InitialisationMachine.as_view()), name='init'),# mac ->nom type
    path(r'machine/debut', csrf_exempt(views.DebutUtilisation.as_view()), name='deb'),# bage mac- autorisation message
    path(r'machine/aide', csrf_exempt(views.Passagedumanager.as_view()), name='aide'),#badge idadmin, max -> autorisation message
    path(r'machine/fin', csrf_exempt(views.FinUtilisation.as_view()), name='fin'),#bage mac- autorisation message
    path(r'machine/veriffin', csrf_exempt(views.VerifFinUtilisation.as_view()), name='verifin'),#bage mac- autorisation message pour verifier les droit de fin
    path('panel/', include('adminpanel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'docapi/', schema_view),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientapp/models.py
from django.db import models

# Create your models here.

clientapp/forms.py
from django import forms

from fabaccess.models import Panne

class IncidentReportForm(forms.ModelForm):

    class Meta:
        model = Panne
        fields = ('machineId', 'cause')

adminpanel/views/machine.py
from django.views import View
from django.http import HttpResponse
from django.template import loader
from adminpanel.forms import *
from django.views.generic import CreateView # new
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from adminpanel.MesDecorateurs import *



#ListMachines du panel qui montre les machines


class ListMachines(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(ListMachines, self).dispatch(*args,**kwargs)


    def get(self,request):
            machines = Machine.objects.all()
            tabmachine=[]
            for machine in machines:
                if machine.libre==0:
                    registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                    machine.user = registre.username.user

                panne = Panne.objects.all().filter(machineId=machine).last()
                if panne:
                    if not panne.fin:
                        machine.panne = 1
                        machine.pannetype = panne.type

                tabmachine.append(machine)
            context = {

                'machines': tabmachine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('adminpanel/index.html')
            return HttpResponse(template.render(context, request))

# visualisation d'une machine et modification de cette dernière
class UneMachine(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(UneMachine, self).dispatch(*args, **kwargs)

    def get(self,request,pk):
            machine=Machine.objects.get(pk=pk)
            if machine.libre==0:
                registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                machine.user = registre.username
            panne = Panne.objects.all().filter(machineId=machine).last()
            if panne:
                if not panne.fin:
                    machine.panne = 1
                    machine.pannetype = panne.type
            form=Machintf(instance=machine)
            context ={
                'form':form,
                'machine':machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template=loader.get_template('adminpanel/machine.html')
            return HttpResponse(template.render(context, request))

    def post(self,request, pk):
            machine=Machine.objects.get(pk=pk)

            if machine.libre==0:
                registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                machine.user = registre.username
            panne = Panne.objects.all().filter(machineId=machine).last()
            if panne:
                if not panne.fin:
                    machine.panne = 1
                    machine.pannetype = panne.type
            form=Machintf(request.POST, request.FILES, instance=machine)
            if form.is_valid():

                form.save()
                machine.type=request.POST['type']
                machine.descriptionLongue=request.POST['descriptionLongue']
                machine.save()
                return redirect('adminpanel:machine',pk=pk)
            else:
                context =  {
                    'form':form,
                    'machine':machine,
                    'duree_timer': 60,
                    'redirection_timer': 'panel/logout'
                }
                template=loader.get_template('adminpanel/machine.html')
                return  HttpResponse(template.render(context, request))


#test pour mettre des images
class IMGMachine(CreateView):
    model = IMG
    form_class = SendIMG
    template_name = 'adminpanel/test.html'
    success_url = reverse_lazy('adminpanel:index')

adminpanel/views/panne.py
from django.views import View
import datetime
from django.utils.timezone import make_aware
from django.http import HttpResponse, JsonResponse
from django.template import loader
import calendar
from adminpanel.MesDecorateurs import *
from django.utils.decorators import method_decorator
from adminpanel.forms import *
import time

#vue pour ajouter une panne
class AjoutPanne(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(AjoutPanne, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
            machine = Machine.objects.get(pk=pk)
            form=PanneForms()
            context = {
                'machine': machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('adminpanel/panne.html')
            return HttpResponse(template.render(context, request))


    def post(self, request, pk):
        detail=request.POST['cause']
        type=request.POST['type']
        machine=Machine.objects.get(pk=pk)
        now = make_aware(datetime.datetime.now())
        if detail=="":
            return redirect('adminpanel:panne', pk=pk)
        else:
            panne = Panne(machineId=machine,type=type, status='declare', debut=now, cause=detail)
            panne.save()
            if type==2:
                machine.operationel = 0
                machine.libre = 1
                machine.save()
            return redirect('adminpanel:index')


# vue pour visualiser, modifier une panne
class VoirPanne(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(VoirPanne, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
            machine = Machine.objects.get(pk=pk)
            panne = Panne.objects.filter(machineId=machine).last()
            context = {
                'panne': panne,
                'machine': machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('adminpanel/panneview.html')
            return HttpResponse(template.render(context, request))


    def post(self, request, pk):
            machine = Machine.objects.get(pk=pk)
            panne = Panne.objects.filter(machineId=machine).last()
            cause = request.POST['cause']
            type = request.POST['type']
            status = request.POST['status']
            if type == '2':
                machine.operationel = 0
                machine.libre = 1
                machine.save()
            else:
                machine.operationel = 1
                machine.save()
            panne.cause = cause
            panne.type = type
            panne.status = status
            panne.save()
            return redirect('adminpanel:panneview', pk=pk)
#vue pour clore une panne

class ClorePanne(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(ClorePanne, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
            now = make_aware(datetime.datetime.now())
            machine = Machine.objects.get(pk=pk)
            panne = Panne.objects.filter(machineId=machine).last()
            panne.status='regle'
            panne.fin=now
            panne.save()
            machine.operationel = 1
            machine.save()
            return redirect('adminpanel:index')


#fonction pour envoyé les stat d'utilisation
#get machine et type de stat voulue
class StatPanne(View):
    def get(self,request):
        para=request.GET['para']
        machine=request.GET['machine']
        today = datetime.date.today()
        seven= today - datetime.timedelta(days=6)
        if para=="week":
            i = 0
            stats = []
            label= []
            labelc=" "
            retenu=0
            while i <7:
                label.append(labelc)

                req = Panne.objects.filter(machineId=machine).filter(debut__day=seven.day)
                seven = seven + datetime.timedelta(days=1)
                if not req:
                    total=0
                else:
                    req.all()
                    total=0
                    for reqs in req:
                        if reqs.fin:
                            total=total+(int(time.mktime(reqs.fin.timetuple()))) - (int(time.mktime(reqs.debut.timetuple())))

                total = total + retenu
                if total >= 24 * 60 * 60:
                    retenu = total - (24 * 60 * 60)
                    total = 24 * 60 * 60
                else:
                    retenu = 0

                total=total/60
                total=round(total,0)
                stats.append(total)
                i += 1
            leg = "Minutes en panne"
        if para=='month':
            i=0
            stats=[]
            label = []
            labelc = " "
            retenu = 0
            month= today -datetime.timedelta(days=29)
            while i <30:
                label.append(labelc)

                req= Panne.objects.filter(machineId=machine).filter(debut__day=month.day)
                month = month+datetime.timedelta(days=1)
                if not req:
                    total=0
                else:
                    req.all()
                    total=0
                    for reqs in req:
                        if reqs.fin:
                            total=total+(int(time.mktime(reqs.fin.timetuple()))) - (int(time.mktime(reqs.debut.timetuple())))

                total = total + retenu
                if total >= 24 * 60 * 60:
                    retenu = total - (24 * 60 * 60)
                    total = 24 * 60 * 60
                else:
                    retenu = 0

                total=total/60
                total = round(total, 0)
                stats.append(total)
                i +=1
            leg="Minutes en panne"

        if para=='year':
            i=0
            stats=[]
            label=[]
            labelc=12
            year=1
            retenu = 0
            while i<12:
                label.append(labelc)
                labelc+=1
                req= Panne.objects.filter(fin__month=year).filter(machineId=machine)
                year=year+1
                if not req:
                    total=0
                else:
                    req.all()
                    total=0
                    for reqs in req:
                        if reqs.fin != 0:
                            total=total+(int(time.mktime(reqs.fin.timetuple()))) - (int(time.mktime(reqs.debut.timetuple())))
                total = total + retenu
                if total >= 24 * 60 * 60 * 30:
                    retenu = total - (24 * 60 * 60 * 30)
                    total = 24 * 60 * 60 * 30
                else:
                    retenu = 0

                total=total/60/60
                total=round(total, 2)
                stats.append(total)
                i+=1
            label=['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai','Juin', 'Juillet','Aout','Septembre','Octobre','Novembre','Decembre']
            leg="Heures en panne"
        return JsonResponse({'stats':stats, 'label':label, 'leg':leg}, safe=False)

clientapp/views/machine.py
from django.http import HttpResponse
from django.template import loader
from django.views import View
import datetime
from fabaccess.models import *
from django.utils.decorators import method_decorator
from adminpanel.MesDecorateurs import *
from django.utils.timezone import make_aware

#affichage des machines
class ListeMachines(View):


    def get(self,request):
            machines=Machine.objects.all()
            tabmachines=[]
            for machine in machines:
                if machine.libre==0:
                    registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                    machine.user=registre.username.user
                panne = Panne.objects.all().filter(machineId=machine).last()
                if panne:
                    if not panne.fin:
                        machine.panne = 1
                        machine.pannetype = panne.type
                tabmachines.append(machine)
            context = {
                'machines': tabmachines,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('clientapp/machines.html')

            return HttpResponse(template.render(context, request))



#Déclaration d'une panne
class DeclarationPanne(View):
    @method_decorator(estunUser())
    def dispatch(self, *args, **kwargs):
        return super(DeclarationPanne, self).dispatch(*args, **kwargs)


    def get(self,request,pk):
            machine=Machine.objects.get(pk=pk)
            context = {
                'machine':machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('clientapp/panne.html')
            return HttpResponse(template.render(context, request))

    def post(self,request,pk):
            machine=Machine.objects.get(pk=pk)
            detail = request.POST['cause']
            now = make_aware(datetime.datetime.now())
            type= request.POST['type']
            panne = Panne(machineId=machine, type=type, status='declare', debut=now, cause=detail)
            panne.save()
            machine.operationel = 0
            machine.libre = 1
            machine.save()
            return redirect('clientapp:machineuser')

class PanneView(View):
    @method_decorator(estunUser())
    def dispatch(self, *args, **kwargs):
        return super(PanneView, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
        machine = Machine.objects.get(pk=pk)
        panne = Panne.objects.filter(machineId=machine).last()
        context = {
            'panne': panne,
            'machine': machine,
            'duree_timer': 60,
            'redirection_timer': 'panel/logout'
        }
        template = loader.get_template('clientapp/panneview.html')
        return HttpResponse(template.render(context, request))

clientapp/templates/clientapp/incidentReport.html
{% extends 'adminpanel/base.html' %}
{% block title %}Fabaccess - Pannes{% endblock %}
{% block content %}
<div>
    <h2>Signaler une panne ou un incident</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
{% endblock %}

clientapp/templates/clientapp/machines.html
{% extends 'adminpanel/base.html' %}
{% block title %}Fabaccess - Machines{% endblock %}

{% load static %}

{% block countdown %}
<div id="timer" class="d-flex justify-content-center align-items-center rounded-circle alert alert-light text-warning my-md-3 mb-1 px-1 font-weight-bold"></div>
{% endblock %}

{% block content %}
{% load static %}

<div class="row justify-content-center px-2">
    <div class="col-12">
        <h2 class="mb-3 mt-0">Liste des machines</h2>
        <div class="row">
            {% for machine in machines %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card {% if not user.is_authenticated %}unlogged-user-machine-card{% endif %} {% if user.is_authenticated %}machine-card{% endif %} mb-4" >
                    <div class="card-body d-flex flex-column px-3 pt-3 pb-2">
                        <div class="d-flex no-wrap mb-1">
                            <div>
                                <a role="button"  data-toggle="modal" data-target="#{{machine.pk}}" href="">
                                    <h5 class="card-title">{{ machine.nom }}</h5>
                                </a>
                                <p class="card-subtitle text-muted mb-3">{{ machine.description }}</p>
                            </div>
                            {% if machine.img %}
                            <img src="{{ machine.img.url }}" class="machine-img ml-auto" alt="{{ machine.nom }}">
                            {% else %}
                            <img src="{% static 'img/cancel.png' %}" class="machine-img ml-auto mr-2" alt="{{ machine.nom }}">
                            {% endif %}
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="{{machine.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-header mb-1 d-flex justify-content-between">
                                        <div class="d-flex align-items-start">
                                            {% if machine.img %}
                                            <img src="{{ machine.img.url }}" class="machine-img ml-auto mr-2" alt="{{ machine.nom }}">
                                            {% else %}
                                            <img src="{% static 'img/cancel.png' %}" class="machine-img ml-auto mr-2" alt="{{ machine.nom }}">
                                            {% endif %}
                                            <h2 class="modal-title" id="exampleModalLongTitle">{{ machine.nom }}</h2>
                                        </div>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body py-2">
                                        <div class="mb-4">
                                            {% if machine.pannetype == 0 or not machine.pannetype %}
                                            {% if machine.libre == 0 %}
                                            <div class="alert alert-secondary container text-center my-2 py-2" role="alert">
                                                <strong>Occupée par {{ machine.user.first_name }}</strong>
                                            </div>
                                            {% elif machine.libre == 1 %}
                                            <div class="alert alert-success container text-center my-2 py-2" role="alert">
                                                <strong>Disponible</strong>
                                            </div>
                                            {% endif %}

                                            {% elif machine.pannetype == 1  %}
                                            {% if machine.libre == 0 %}
                                            <div class="alert alert-secondary container text-center my-2 py-2" role="alert">
                                                <strong>Occupée par {{ machine.user.first_name }}</strong>
                                            </div>
                                            {% elif machine.libre == 1 %}
                                            <div class="alert alert-warning container text-center my-2 py-2" role="alert">
                                                <strong>Utilisation restreinte</strong>
                                            </div>
                                            {% endif %}

                                            {% elif machine.pannetype == 2 %}
                                            <div class="alert alert-danger container text-center my-2 py-2" role="alert">
                                                <strong>Hors-service</strong>
                                            </div>
                                            {% endif %}
                                        </div>
                                        <h6 class="">Description</h6>
                                        <p class="mb-4">{{ machine.descriptionLongue }}</p>
                                        <div class="row">
                                            <div class="col-8">
                                                <h6 class="">Mode d'utilisation</h6>
                                                {% if machine.type == 'fixe' %}
                                                <p class=""><strong>Présence obligatoire pendant toute la durée d'utilisation :</strong><br>je pose mon badge sur le lecteur.</p>
                                                {% elif machine.type == 'mobile' %}
                                                <p class=""><strong>Présence facultative pendant l'utilisation :</strong><br>je passe mon badge devant le lecteur.</p>
                                                {% endif %}
                                            </div>
                                            <div class="col-4">
                                                <h6 class="">Coût d'utilisation</h6>
                                                <p class="">{{ machine.cout }}</p>
                                            </div>
                                        </div>
                                    </div>
                                    {% if user.is_authenticated %}
                                    <div class="modal-footer py-2 d-flex justify-content-end">

                                        {% if  machine.pannetype == 0 or machine.pannetype == 1 or machine.pannetype == 2 %}
                                        <a class="btn btn-sm btn-warning btn-raised" href="{% url 'clientapp:panneview' pk=machine.pk%}">
                                            Consulter les incidents
                                        </a>
                                        {% else %}
                                        <a class="btn btn-sm btn-secondary btn-raised" href="{% url 'clientapp:panne' pk=machine.pk%}">
                                            Déclarer un incident
                                        </a>
                                        <div class="machine-card-gap">

                                        </div>
                                        {% endif %}
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="mt-auto">
                            {% if machine.pannetype == 0 or not machine.pannetype %}
                            {% if machine.libre == 0 %}
                            <div class="alert alert-secondary container text-center my-2 py-2" role="alert">
                                <strong>Occupée par {{ machine.user.first_name }}</strong>
                            </div>
                            {% elif machine.libre == 1 %}
                            <div class="alert alert-success container text-center my-2 py-2" role="alert">
                                <strong>Disponible</strong>
                            </div>
                            {% endif %}

                            {% elif machine.pannetype == 1  %}
                            {% if machine.libre == 0 %}
                            <div class="alert alert-secondary container text-center my-2 py-2" role="alert">
                                <strong>Occupée par {{ machine.user.first_name }}</strong>
                            </div>
                            {% elif machine.libre == 1 %}
                            <div class="alert alert-warning container text-center my-2 py-2" role="alert">
                                <strong>Utilisation restreinte</strong>
                            </div>
                            {% endif %}

                            {% elif machine.pannetype == 2 %}
                            <div class="alert alert-danger container text-center my-2 py-2" role="alert">
                                <strong>Hors-service</strong>
                            </div>
                            {% endif %}
                        </div>




                        <div class="d-flex justify-content-end">
                            {% if user.is_authenticated %}
                            {% if  machine.pannetype == 0 or machine.pannetype == 1 or machine.pannetype == 2 %}
                            <a class="btn btn-sm btn-warning btn-raised" href="{% url 'clientapp:panneview' pk=machine.pk%}">
                                Consulter les incidents
                            </a>
                            {% else %}
                            <a class="btn btn-sm btn-secondary btn-raised" href="{% url 'clientapp:panne' pk=machine.pk%}">
                                Déclarer un incident
                            </a>
                            <div class="machine-card-gap">

                            </div>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block countdownscript %}
{% if user.is_authenticated %}
<script type="text/javascript">
    var duree_timer = '{{duree_timer}}';
    var redirection_timer = '{{redirection_timer}}';
</script>
{% else %}
<script type="text/javascript">
    var duree_timer = '{{duree_timer}}';
    var redirection_timer = '';
</script>
{% endif %}
<script type="text/javascript" src="{% static 'js/countdown.js' %}"></script>
{% endblock %}

clientapp/templates/clientapp/profile.html
{% extends 'adminpanel/base.html' %}
{% block title %}Fabaccess - Profil{% endblock %}

{% load static %}

{% block countdown %}
<div id="timer" class="d-flex justify-content-center align-items-center rounded-circle alert alert-light text-warning my-md-3 mb-1 px-1 font-weight-bold"></div>
{% endblock %}

{% block content %}
{% if msg %}
<div class="alert alert-danger" role="alert">
    {{ msg }}
</div>
{% endif %}

<div class="row justify-content-center px-2">
    <div class="col-12">
        <h2 class="mb-3 mt-0">Mon profil</h2>
        <div class="row justify-content-center">
            <div class="card container mb-3 p-4">
                <div class="card-body">
                    <form method="post" action="{% url 'clientapp:user' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleInputEmail1" class="bmd-label-floating">Nom</label>
                            <input type="text" class="form-control text-center" name="Nom" autofocus="" required="" id="Nom" value="{{ user.last_name }}">
                            <!-- <span class="bmd-help">We'll never share your email with anyone else.</span> -->
                        </div>
                        <div class="form-group">
                            <label for="Prenom" class="bmd-label-floating">Prénom</label>
                            <input type="text" class="form-control text-center" name="Prenom" autofocus="" required="" id="Prenom" value="{{ user.first_name }}">
                        </div>
                        <div class="form-group">
                            <label for="Email" class="bmd-label-floating">Adresse mail</label>
                            <input type="text" class="form-control text-center" value="{{ user.email }}" type="text" name="Email" id="Email">
                        </div>
                        <div class="form-group">
                            <!-- <label for="Doliid" class="bmd-label-floating">Compte Dolibarr</label> -->
                            <input type="hidden" class="form-control text-center" readonly value="{{ userdata1.doliid }}" type="text" name="Doliid" id="Doliid">
                        </div>

                        <input type="hidden" name="next" value="{{ next }}">
                        <div class="d-flex justify-content-end mt-4">
                            <button type="submit" value="login" class="btn btn-sm btn-raised btn-success">Enregistrer</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block countdownscript %}
<script type="text/javascript">
    var duree_timer = '{{duree_timer}}';
    var redirection_timer = '{{redirection_timer}}';
</script>
<script type="text/javascript" src="{% static 'js/countdown.js' %}"></script>
{% endblock %}