adminpanel/urls.py
from django.urls import path
from adminpanel import views
from django.views.decorators.csrf import csrf_exempt


app_name = 'adminpanel'
urlpatterns = [
    path(r'', views.ListMachines.as_view(), name='index'),
    path(r'logout', views.Logout.as_view(), name='logout'),
    path(r'machine/<int:pk>', views.machine.UneMachine.as_view(), name="machine"),
    path(r'panne/<int:pk>', views.AjoutPanne.as_view(), name='panne'),
    path(r'panneview/<int:pk>', views.VoirPanne.as_view(), name='panneview'),
    path(r'pannefin/<int:pk>', views.ClorePanne.as_view(), name='pannefin'),

    path(r'userindex', views.ListeUtilisateur.as_view(), name='userindex'),
    path(r'usersearch', views.RechercheUtilisateur.as_view(), name='search'),
    path(r'userview/<int:pk>', views.VueUtilisateur.as_view(), name="user"),
    path(r'userstat/<int:pk>', views.StatUtilisateur.as_view(), name="userstat"),
    path(r'useradd', views.Ajoututilisateur.as_view(), name="useradd"),
    path(r'droit/<int:pk>', csrf_exempt(views.DroitUtilisateur.as_view()), name='userdroit'),



    path(r'log/<str:badgetag>', csrf_exempt(views.Login.as_view()), name='log'),
    path(r'attentebadge/<int:pk>', csrf_exempt(views.Attente.as_view()), name='attentebadge'),
    path(r'envoiedubadge', csrf_exempt(views.EnregistrementBadge.as_view()), name='enregistrement'),
    path(r'verifyonline', views.VerifyOnline.as_view(), name='verifyonline'),


    path(r'imgadd', views.IMGMachine.as_view(), name="image"),

    path(r'doliimport', views.ImportationDolibarr.as_view(), name="import"),

    path(r'option', views.Option.as_view(), name='option'),

    #test
    path(r'stat/<int:pk>', views.VueStatistiques.as_view(), name='chart'),
    path(r'statp', views.StatPanne.as_view(), name='chatpanne'),
    path(r'teststat', views.StatsUtilisationMachine.as_view(), name="test"),

]

clientapp/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt


app_name = 'clientapp'
urlpatterns = [
    path(r'', views.Accueil.as_view(), name='index'),
    path(r'aide', views.Aide.as_view(), name='aide'),
    path(r'bienvenu', csrf_exempt(views.ArriveeDepartUtilisateur.as_view()), name='welcome'),
    path(r'accueilJS', views.AccueilJS.as_view(), name='indexJS'),
    path(r'connexion', csrf_exempt(views.ClientLogin.as_view()), name='log'),
    path(r'message', views.MessageAccueil.as_view(), name='message'),
    path(r'user', views.Profil.as_view(), name='user'),
    path(r'statistiques', views.Stats.as_view(), name='stats'),
    path(r'machine', views.ListeMachines.as_view(), name="machineuser"),
    path(r'panne/<int:pk>', views.DeclarationPanne.as_view(), name="panne"),
    path(r'panneview/<int:pk>', views.PanneView.as_view(), name="panneview"),

    path(r'borneclient',views.Websocket.as_view(),name="borneclient")
]

configuration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from rest_framework import routers
from fabaccess import views
from django.views.decorators.csrf import csrf_exempt
from rest_framework_swagger.views import get_swagger_view
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'userdata', views.UserdataViewSet)
router.register(r'machine', views.MachineViewSet)
router.register(r'registremanchine', views.RegistreMachineViewSet)
router.register(r'registreentree', views.RegistreEntreeViewSet)
router.register(r'panne', views.PanneViewSet)
router.register(r'droit', views.DroitViewSet)

schema_view = get_swagger_view(title='Fabacces API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientapp.urls')),
    path('api/',include(router.urls)),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'machine/init', csrf_exempt(views.InitialisationMachine.as_view()), name='init'),# mac ->nom type
    path(r'machine/debut', csrf_exempt(views.DebutUtilisation.as_view()), name='deb'),# bage mac- autorisation message
    path(r'machine/aide', csrf_exempt(views.Passagedumanager.as_view()), name='aide'),#badge idadmin, max -> autorisation message
    path(r'machine/fin', csrf_exempt(views.FinUtilisation.as_view()), name='fin'),#bage mac- autorisation message
    path(r'machine/veriffin', csrf_exempt(views.VerifFinUtilisation.as_view()), name='verifin'),#bage mac- autorisation message pour verifier les droit de fin
    path('panel/', include('adminpanel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'docapi/', schema_view),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from fabaccess.models import *

class SignUpForm(UserCreationForm):
    email= forms.CharField(max_length=200)
    nom= forms.CharField(max_length=200)
    prenom= forms.CharField(max_length=200)

    class Meta:
        model = User
        fields = ('username','nom','prenom','email','password1','password2')


class SendIMG(forms.ModelForm):

    class Meta:
        model = IMG
        fields = ['titre','image']

class Machintf(forms.ModelForm):

    class Meta:
        model=Machine
        fields=('nom','description','img','cout')


class PanneForms(forms.ModelForm):

    class Meta:
        model=Panne
        fields=('machineId','type','status','cause')

adminpanel/views/machine.py
from django.views import View
from django.http import HttpResponse
from django.template import loader
from adminpanel.forms import *
from django.views.generic import CreateView # new
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from adminpanel.MesDecorateurs import *



#ListMachines du panel qui montre les machines


class ListMachines(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(ListMachines, self).dispatch(*args,**kwargs)


    def get(self,request):
            machines = Machine.objects.all()
            tabmachine=[]
            for machine in machines:
                if machine.libre==0:
                    registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                    machine.user = registre.username.user

                panne = Panne.objects.all().filter(machineId=machine).last()
                if panne:
                    if not panne.fin:
                        machine.panne = 1
                        machine.pannetype = panne.type

                tabmachine.append(machine)
            context = {

                'machines': tabmachine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('adminpanel/index.html')
            return HttpResponse(template.render(context, request))

# visualisation d'une machine et modification de cette dernière
class UneMachine(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(UneMachine, self).dispatch(*args, **kwargs)

    def get(self,request,pk):
            machine=Machine.objects.get(pk=pk)
            if machine.libre==0:
                registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                machine.user = registre.username
            panne = Panne.objects.all().filter(machineId=machine).last()
            if panne:
                if not panne.fin:
                    machine.panne = 1
                    machine.pannetype = panne.type
            form=Machintf(instance=machine)
            context ={
                'form':form,
                'machine':machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template=loader.get_template('adminpanel/machine.html')
            return HttpResponse(template.render(context, request))

    def post(self,request, pk):
            machine=Machine.objects.get(pk=pk)

            if machine.libre==0:
                registre = RegistreMachine.objects.all().filter(machineId=machine).last()
                machine.user = registre.username
            panne = Panne.objects.all().filter(machineId=machine).last()
            if panne:
                if not panne.fin:
                    machine.panne = 1
                    machine.pannetype = panne.type
            form=Machintf(request.POST, request.FILES, instance=machine)
            if form.is_valid():

                form.save()
                machine.type=request.POST['type']
                machine.descriptionLongue=request.POST['descriptionLongue']
                machine.save()
                return redirect('adminpanel:machine',pk=pk)
            else:
                context =  {
                    'form':form,
                    'machine':machine,
                    'duree_timer': 60,
                    'redirection_timer': 'panel/logout'
                }
                template=loader.get_template('adminpanel/machine.html')
                return  HttpResponse(template.render(context, request))


#test pour mettre des images
class IMGMachine(CreateView):
    model = IMG
    form_class = SendIMG
    template_name = 'adminpanel/test.html'
    success_url = reverse_lazy('adminpanel:index')

adminpanel/views/panne.py
from django.views import View
import datetime
from django.utils.timezone import make_aware
from django.http import HttpResponse, JsonResponse
from django.template import loader
import calendar
from adminpanel.MesDecorateurs import *
from django.utils.decorators import method_decorator
from adminpanel.forms import *
import time

#vue pour ajouter une panne
class AjoutPanne(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(AjoutPanne, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
            machine = Machine.objects.get(pk=pk)
            form=PanneForms()
            context = {
                'machine': machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('adminpanel/panne.html')
            return HttpResponse(template.render(context, request))


    def post(self, request, pk):
        detail=request.POST['cause']
        type=request.POST['type']
        machine=Machine.objects.get(pk=pk)
        now = make_aware(datetime.datetime.now())
        if detail=="":
            return redirect('adminpanel:panne', pk=pk)
        else:
            panne = Panne(machineId=machine,type=type, status='declare', debut=now, cause=detail)
            panne.save()
            if type==2:
                machine.operationel = 0
                machine.libre = 1
                machine.save()
            return redirect('adminpanel:index')


# vue pour visualiser, modifier une panne
class VoirPanne(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(VoirPanne, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
            machine = Machine.objects.get(pk=pk)
            panne = Panne.objects.filter(machineId=machine).last()
            context = {
                'panne': panne,
                'machine': machine,
                'duree_timer': 60,
                'redirection_timer': 'panel/logout'
            }
            template = loader.get_template('adminpanel/panneview.html')
            return HttpResponse(template.render(context, request))


    def post(self, request, pk):
            machine = Machine.objects.get(pk=pk)
            panne = Panne.objects.filter(machineId=machine).last()
            cause = request.POST['cause']
            type = request.POST['type']
            status = request.POST['status']
            if type == '2':
                machine.operationel = 0
                machine.libre = 1
                machine.save()
            else:
                machine.operationel = 1
                machine.save()
            panne.cause = cause
            panne.type = type
            panne.status = status
            panne.save()
            return redirect('adminpanel:panneview', pk=pk)
#vue pour clore une panne

class ClorePanne(View):
    @method_decorator(estAdmin())
    def dispatch(self, *args, **kwargs):
        return super(ClorePanne, self).dispatch(*args, **kwargs)

    def get(self, request, pk):
            now = make_aware(datetime.datetime.now())
            machine = Machine.objects.get(pk=pk)
            panne = Panne.objects.filter(machineId=machine).last()
            panne.status='regle'
            panne.fin=now
            panne.save()
            machine.operationel = 1
            machine.save()
            return redirect('adminpanel:index')


#fonction pour envoyé les stat d'utilisation
#get machine et type de stat voulue
class StatPanne(View):
    def get(self,request):
        para=request.GET['para']
        machine=request.GET['machine']
        today = datetime.date.today()
        seven= today - datetime.timedelta(days=6)
        if para=="week":
            i = 0
            stats = []
            label= []
            labelc=" "
            retenu=0
            while i <7:
                label.append(labelc)

                req = Panne.objects.filter(machineId=machine).filter(debut__day=seven.day)
                seven = seven + datetime.timedelta(days=1)
                if not req:
                    total=0
                else:
                    req.all()
                    total=0
                    for reqs in req:
                        if reqs.fin:
                            total=total+(int(time.mktime(reqs.fin.timetuple()))) - (int(time.mktime(reqs.debut.timetuple())))

                total = total + retenu
                if total >= 24 * 60 * 60:
                    retenu = total - (24 * 60 * 60)
                    total = 24 * 60 * 60
                else:
                    retenu = 0

                total=total/60
                total=round(total,0)
                stats.append(total)
                i += 1
            leg = "Minutes en panne"
        if para=='month':
            i=0
            stats=[]
            label = []
            labelc = " "
            retenu = 0
            month= today -datetime.timedelta(days=29)
            while i <30:
                label.append(labelc)

                req= Panne.objects.filter(machineId=machine).filter(debut__day=month.day)
                month = month+datetime.timedelta(days=1)
                if not req:
                    total=0
                else:
                    req.all()
                    total=0
                    for reqs in req:
                        if reqs.fin:
                            total=total+(int(time.mktime(reqs.fin.timetuple()))) - (int(time.mktime(reqs.debut.timetuple())))

                total = total + retenu
                if total >= 24 * 60 * 60:
                    retenu = total - (24 * 60 * 60)
                    total = 24 * 60 * 60
                else:
                    retenu = 0

                total=total/60
                total = round(total, 0)
                stats.append(total)
                i +=1
            leg="Minutes en panne"

        if para=='year':
            i=0
            stats=[]
            label=[]
            labelc=12
            year=1
            retenu = 0
            while i<12:
                label.append(labelc)
                labelc+=1
                req= Panne.objects.filter(fin__month=year).filter(machineId=machine)
                year=year+1
                if not req:
                    total=0
                else:
                    req.all()
                    total=0
                    for reqs in req:
                        if reqs.fin != 0:
                            total=total+(int(time.mktime(reqs.fin.timetuple()))) - (int(time.mktime(reqs.debut.timetuple())))
                total = total + retenu
                if total >= 24 * 60 * 60 * 30:
                    retenu = total - (24 * 60 * 60 * 30)
                    total = 24 * 60 * 60 * 30
                else:
                    retenu = 0

                total=total/60/60
                total=round(total, 2)
                stats.append(total)
                i+=1
            label=['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai','Juin', 'Juillet','Aout','Septembre','Octobre','Novembre','Decembre']
            leg="Heures en panne"
        return JsonResponse({'stats':stats, 'label':label, 'leg':leg}, safe=False)

adminpanel/templates/adminpanel/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}{% endblock %}
    </title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <!-- Material Design for Bootstrap fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script>

        var baseurl="{{ request.scheme }}://{{ request.get_host }}{% url 'clientapp:index' %}";

</script>


</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light top-bar top-bar-bg fixed-top px-2 pr-md-3 pl-md-4">
        <a class="navbar-brand mt-md-1 navlink"  href="{% url 'clientapp:index' %}">
            <h1 class="top-bar-title top-bar-text">FabAccess</h1>
        </a>
        {% block countdown %}
        {% endblock %}

        <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse box-shadow top-bar-bg" id="navbar-menu">
            <!-- {{request.path}} -->
            <ul class="navbar-nav mt-1 mt-md-2 ml-auto pb-2">
                {% if user.is_authenticated %}
                    {% if user.userdata.type == 'Fabmanager' or user.userdata.type == 'Concierge' %}

                    <li class="nav-item ml-auto mr-4">
                        <a class="nav-link navlink top-bar-text {% if request.path == '/panel/' or '/machine/' in request.path or '/stat/' in request.path or '/panne/' in request.path or '/panneview/' in request.path %}nav-link-active{% endif %}" href="{% url 'adminpanel:index' %}">Machines</a>
                    </li>
                    <li class="nav-item ml-auto mr-4">
                        <a class="nav-link navlink top-bar-text {% if request.path == '/panel/userindex' or '/userview/' in request.path or '/useradd' in request.path or '/droit/' in request.path or '/attentebadge/' in request.path or '/userstat/' in request.path %}nav-link-active{% endif %}" href="{% url 'adminpanel:userindex' %}">Membres</a>
                    </li>
                    <li class="nav-item ml-auto mr-4">
                        <a class="nav-link navlink top-bar-text {% if request.path == '/panel/option' %}nav-link-active{% endif %}" href="{% url 'adminpanel:option' %}">Options</a>
                    </li>
                    {% endif %}

                    {% if user.userdata.type == 'User' %}
                    <li class="nav-item ml-auto mr-4">
                        <a class="nav-link navlink top-bar-text {% if request.path == '/machine' or '/panne/' in request.path or '/panneview/' in request.path %}nav-link-active{% endif %}" href="{% url 'clientapp:machineuser' %}">Machines</a>
                    </li>
                    <li class="nav-item ml-auto mr-4">
                        <a class="nav-link navlink top-bar-text {% if request.path == '/statistiques' %}nav-link-active{% endif %}" href="{% url 'clientapp:stats' %}">Stats</a>
                    </li>
                    <li class="nav-item ml-auto mr-4">
                        <a class="nav-link navlink top-bar-text {% if request.path == '/user' %}nav-link-active{% endif %}" href="{% url 'clientapp:user' %}">Profil</a>
                    </li>

                    {% endif %}
                    <li class="nav-item navlink ml-auto mr-4">
                        <a class="nav-link top-bar-text {% if request.path == '/aide' %}nav-link-active{% endif %}" href="{% url 'clientapp:aide' %}">Aide</a>
                    </li>
                    <li class="nav-item navlink ml-auto mr-4">
                        <a id="logout" class="nav-link top-bar-text" href="{% url 'adminpanel:logout' %}?next={% url 'clientapp:index' %}">Déconnexion</a>
                    </li>
                {% endif %}

                {% if not user.is_authenticated %}
                <li class="nav-item navlink ml-auto mr-4">
                    <a class="nav-link top-bar-text {% if request.path == '/machine' %}nav-link-active{% endif %}" href="{% url 'clientapp:machineuser' %}">Machines</a>
                </li>
                <li class="nav-item navlink ml-auto mr-4">
                    <a class="nav-link top-bar-text {% if request.path == '/aide' %}nav-link-active{% endif %}" href="{% url 'clientapp:aide' %}">Aide</a>
                </li>
                <li class="nav-item navlink ml-auto mr-4">
                    <a class="nav-link top-bar-text" href="{% url 'login' %}?next={% url 'clientapp:index' %}">Connexion</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </nav>
    <main class="container-fluid pt-4">
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        {% block footer %}
        {% endblock %}
    </footer>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('body').bootstrapMaterialDesign();
        });
    </script>
    {% block countdownscript %}
    {% endblock %}


    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
</body>

</html>

adminpanel/templates/adminpanel/bonjour.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block title %}Machines{% endblock %}

{% block countdown %}
<div id="timer" class="d-flex justify-content-center align-items-center rounded-circle alert alert-light text-warning my-md-3 mb-1 px-1 font-weight-bold"></div>
{% endblock %}

{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center">
    <h2 class="mb-4">Bienvenue, {{user1.first_name}}</h2>
</div>

<script>
$(function () {
    let username = "{{user1.first_name}}"
    let socket = new WebSocket("ws://127.0.0.1:5678/")

    let msg=JSON.stringify({
        "action":"arretLecture",
        "msg":"Bienvenue, " + username,
    });
    socket.onopen =function (e) {
        console.log(e)
        socket.send(msg);
    };
    socket.onmessage= function (event) {
        console.log(event)
    };
    socket.onerror=function(error){
        console.log(error)
    };
})
</script>

{% endblock %}

{% block countdownscript %}
<script type="text/javascript">
    var duree_timer = '{{duree_timer}}';
    var redirection_timer = '{{redirection_timer}}';
</script>
<script type="text/javascript" src="{% static 'js/countdown.js' %}"></script>
{% endblock %}

adminpanel/templates/adminpanel/userindex.html
{% extends 'adminpanel/base.html' %}

{% block title %}Utilisateur{% endblock %}

{% load static %}

{% block countdown %}
<div id="timer" class="d-flex justify-content-center align-items-center rounded-circle alert alert-light text-warning my-md-3 mb-1 px-1 font-weight-bold"></div>
{% endblock %}

{% block content %}
<div class="row justify-content-center px-2">
    <div class="col-12">
        <div class="d-flex align-items-start mb-3 mt-0">
            <h2 class="">Liste des membres</h2>
            <p class="mt-2 ml-auto mr-2">Rechercher un membre</p>
            <div class="bmd-form-group bmd-collapse-inline pull-xs-left">
                <button class="btn bmd-btn-icon btn-search" for="search" data-toggle="collapse" data-target="#collapse-search" aria-expanded="false" aria-controls="collapse-search">
                    <i class="material-icons">search</i>
                </button>
                <span id="collapse-search" class="collapse">
                <form class="" action="{% url 'adminpanel:search' %}" method="get">
                    <input class="form-control" name="q" type="text" id="search" placeholder=" Entrez un prénom">
                </form>
                </span>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-sm-7">
                <p class="text-justify">Les membres présents sont affichés en bleu, les membres actif en blanc et les membres inactifs en gris.
                Seuls les membres actifs sont listés par défaut. Utilisez la recherche pour trouver un membre inactif.</p>
            </div>
            <div class="col-12 col-sm-5">
                <div class="d-flex align-items-end flex-column">
                    <div class="d-flex flex-wrap justify-content-end">
                        <a id="link" style="display: block" href="{% url 'adminpanel:useradd' %}">
                            <button type="button" value="login" class="btn btn-sm btn-raised btn-success">Ajouter un membre</button>
                        </a>
                        {% if doliactive == '1' %}
                        <a id="link" style="display: block" href="{% url 'adminpanel:import' %}">
                            <button type="button" value="login" class="btn btn-sm btn-raised btn-info">Importer via Dolibarr</button>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% if msg %}
        <div class="alert container text-center alert-success" role="alert">
            {{ msg }}
        </div>
        {% endif %}
        <div class="row mb-3">
            {% for user in users %}
            <div class="col-12 col-sm-6 col-md-4">
                <div class="card mb-4 {% if doliactive == '0' %}user-card{% endif %} {% if doliactive == '1' %}doli-user-card{% endif %} {% if user.userdata.online == 1 %}logged-user-card {% endif %} {% if user.userdata.active == 0 %}bg-light{% endif %}">
                    <div class="card-body d-flex flex-column px-3 pt-3 pb-2">
                        <div class="d-flex flex-wrap">
                            <a href="{% url 'adminpanel:user' pk=user.pk%}" class="mb-2">
                                {% if user.userdata.active == 1 %}
                                <h6 class="{% if user.userdata.online == 1 %}logged-user-card {% endif %}">{{ user.first_name }}<br>{{ user.last_name }}</h6>
                                {% elif user.userdata.active == 0 %}
                                <h6 class="card-title text-muted">{{ user.first_name }}<br>{{ user.last_name }}</h6>
                                {% endif %}
                            </a>
                            {% if user.userdata.type == 'User' %}
                            <small class="ml-auto">Membre</small>
                            {% else %}
                            <small class="ml-auto">{{ user.userdata.type }}</small>
                            {% endif %}

                        </div>

                        {% if doliactive == '1' %}
                        <div class="d-flex justify-content-center mt-auto">
                            {% if user.userdata.subscription == 0 %}
                            <div class="alert container alert-secondary text-center mb-2 py-1" role="alert">
                                Non adhérent
                            </div>
                            {% elif user.userdata.subscription < now %}
                            <div class="alert container alert-warning text-center mb-2 py-1" role="alert">
                                Cotisation échue
                            </div>
                            {% elif user.userdata.subscription > now %}
                            <div class="alert container alert-success text-center mb-2 py-1" role="alert">
                                Adhérent
                            </div>
                            {% endif %}
                        </div>
                        {% endif %}
                        <div class="d-flex justify-content-end {% if doliactive == '0' %}mt-auto{% endif %}">
                            <a class="btn btn-sm {% if user.userdata.online == 1 %}btn-logged-user{% else %} btn-unlogged-user {% endif %} btn-raised" href="{% url 'adminpanel:userstat' pk=user.pk %}">Stats</a>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

{% block countdownscript %}
<script type="text/javascript">
    var duree_timer = '{{duree_timer}}';
    var redirection_timer = '{{redirection_timer}}';
</script>
<script type="text/javascript" src="{% static 'js/countdown.js' %}"></script>
{% endblock %}